export const students = [
  {
    id: "1",
    name: "Alex Johnson",
    enrollmentNumber: "EN2023001",
    department: "Computer Science",
    batch: "2023-2027",
    contactNumber: "+1 (555) 123-4567",
    profileImage: "/placeholder.svg?height=400&width=400",
    category: "Undergraduate",
    description:
      "Alex is a first-year computer science student with a passion for artificial intelligence and machine learning. He has participated in several hackathons and coding competitions.",
    uploadedMedia: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    socialMedia: {
      facebook: "https://facebook.com",
      twitter: "https://twitter.com",
      instagram: "https://instagram.com",
      linkedin: "https://linkedin.com",
    },
  },
  {
    id: "2",
    name: "Samantha Lee",
    enrollmentNumber: "EN2022045",
    department: "Electrical Engineering",
    batch: "2022-2026",
    contactNumber: "+1 (555) 987-6543",
    profileImage: "/placeholder.svg?height=400&width=400",
    category: "Undergraduate",
    description:
      "Samantha is an electrical engineering student with a focus on renewable energy systems. She is currently working on a solar panel efficiency project.",
    uploadedMedia: ["/placeholder.svg?height=300&width=400"],
    socialMedia: {
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
      linkedin: "https://linkedin.com",
    },
  },
  {
    id: "3",
    name: "Michael Chen",
    enrollmentNumber: "EN2021078",
    department: "Business Administration",
    batch: "2021-2025",
    contactNumber: "+1 (555) 234-5678",
    profileImage: "/placeholder.svg?height=400&width=400",
    category: "Undergraduate",
    description:
      "Michael is a business administration student specializing in entrepreneurship. He has already launched two successful startups while studying.",
    uploadedMedia: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    socialMedia: {
      twitter: "https://twitter.com",
      linkedin: "https://linkedin.com",
    },
  },
  {
    id: "4",
    name: "Emily Rodriguez",
    enrollmentNumber: "EN2020112",
    department: "Mechanical Engineering",
    batch: "2020-2024",
    contactNumber: "+1 (555) 345-6789",
    profileImage: "/placeholder.svg?height=400&width=400",
    category: "Undergraduate",
    description:
      "Emily is a mechanical engineering student focusing on automotive design. She is part of the university's Formula SAE team and has interned at Tesla.",
    uploadedMedia: [],
    socialMedia: {
      instagram: "https://instagram.com",
      linkedin: "https://linkedin.com",
    },
  },
  {
    id: "5",
    name: "David Kim",
    enrollmentNumber: "EN2022033",
    department: "Physics",
    batch: "2022-2026",
    contactNumber: "+1 (555) 456-7890",
    profileImage: "/placeholder.svg?height=400&width=400",
    category: "Undergraduate",
    description:
      "David is a physics student with a particular interest in quantum mechanics. He is currently assisting in research at the university's quantum computing lab.",
    uploadedMedia: ["/placeholder.svg?height=300&width=400"],
    socialMedia: {
      facebook: "https://facebook.com",
      twitter: "https://twitter.com",
    },
  },
  {
    id: "6",
    name: "Olivia Wilson",
    enrollmentNumber: "EN2021056",
    department: "Psychology",
    batch: "2021-2025",
    contactNumber: "+1 (555) 567-8901",
    profileImage: "/placeholder.svg?height=400&width=400",
    category: "Undergraduate",
    description:
      "Olivia is a psychology student focusing on clinical psychology. She volunteers at the campus counseling center and is conducting research on anxiety disorders.",
    uploadedMedia: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    socialMedia: {
      instagram: "https://instagram.com",
      linkedin: "https://linkedin.com",
    },
  },
]
